[package]
name = "buffdb"
authors = ["Marcus Eagan"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.30.0"
tonic = "0.10.2"
prost = "0.12.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "io-util", "sync", "net"] }

[build-dependencies]
tonic-build = "0.10.2"
prost-build = "0.12.3"