[package]
name = "buffdb"
authors = ["Marcus Eagan"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
once_cell = "1.19.0"
prost = "0.13.1"
rusqlite = "0.32.0"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "io-util",
    "sync",
    "net",
] }
tokio-stream = "0.1.15"
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
prost-build = "0.13.1"
