[package]
name = "buffdb"
authors = ["Marcus Eagan", "Jacob Pratt"]
version = "0.1.0"
edition = "2021"
description = "Embedded storage at the speed of light."
repository = "https://github.com/buffdb/buffdb"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["database", "storage", "embedded", "key-value", "blob"]
categories = ["database-implementations", "embedded"]

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
once_cell = "1.19.0"
prost = "0.13.1"
rusqlite = "0.32.0"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "io-util",
    "sync",
    "net",
] }
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
