[package]
name = "buffdb"
authors = ["Marcus Eagan"]
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32.0"
tonic = "0.12.1"
prost = "0.13.1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "io-util",
    "sync",
    "net",
] }
tokio-stream = "0.1.15"

[build-dependencies]
tonic-build = "0.12.1"
prost-build = "0.13.1"
