[package]
name = "buffdb"
authors = ["Marcus Eagan", "Jacob Pratt"]
version = "0.1.1"
edition = "2021"
description = "Embedded storage at the speed of light."
repository = "https://github.com/buffdb/buffdb"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["database", "storage", "embedded", "key-value", "blob"]
categories = ["database-implementations", "embedded"]

[[bin]]
name = "buffdb"
required-features = ["binary"]

[features]
default = []
binary = ["dep:anyhow", "dep:clap"]

[dependencies]
anyhow = { version = "1.0.86", optional = true }
clap = { version = "4.5.10", features = ["derive"], optional = true }
prost = "0.13.1"
rand = "0.8.5"
rocksdb = { version = "0.22.0", default-features = false, features = ["zstd"] }
tokio = { version = "1", features = ["rt-multi-thread", "fs"] }
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
